### PR TITLE
Allow to send the URI as parameter without having to use --uri

### PR DESCRIPTION
**Pull request by lefred**
like: 

`$ dolphie mysql://root:password@127.0.0.1`

This is to be more inline with the standard way to use it like MySQL Shell

### CODE REVIEW

**Comment by charles-001** [comment]
Does it make since to remove `--uri` with this change @lefred ?

**Comment by lefred** [comment]
Currently I left it in case some pple prefer that way. It's up to you or other users to decide ;-)

**Comment by charles-001** [comment]
I think it makes sense to not support `--uri` since it's an optional positional arguement. Can you remove it in the code + README? I can as well if you prefer.

**Comment by charles-001** [comment]
I went ahead and merged this - I will remove `--uri` to fully support this optional positional arguement. Thank you for the suggestion @lefred !

**Pull request merged**
